algoritmo "decremento_simples"
var
   numero1, resultado: real

inicio
   escreval("----------------------------------------")
   escreval("         DECREMENTO DE UM NÚMERO        ")
   escreval("----------------------------------------")

   escreva("Digite um número: ")
   leia(numero1)

   resultado <- numero1 - 1

   escreval("O resultado de ", numero1:4:2, " - 1 é igual a: ", resultado:4:2)
   escreval("----------------------------------------")
fimalgoritmo
