algoritmo "soma_simples"
var
   n1, n2, r: inteiro

inicio
   escreval("------------------------------")
   escreval("          VAMOS SOMAR!        ")
   escreval("------------------------------")

   escreva("Digite um número: ")
   leia(n1)

   escreva("Digite outro número: ")
   leia(n2)

   r <- n1 + n2

   escreval("O resultado da soma de ", n1, " + ", n2, " é igual a ", r, "!")
fimalgoritmo
